name: Compile AutoHotkey Script and Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install AutoHotkey
      run: choco install autohotkey.portable
      
    - name: Compile script
      run: autohotkey.exe /compile /in "*.ahk" /out "*.exe"
      
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          Compiled AutoHotkey script
        draft: false
        prerelease: false

    - name: Upload files to release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "*.exe"
        asset_name: your_script_${{ github.run_number }}.exe
        asset_content_type: application/octet-stream
