name: Compile AutoHotkey Script and Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Compile with Ahk2Exe
        id: ahk2exe
        uses: cennis91/action-ahk2exe@main
        with:
          in: src/*.ahk
